### ISSUE TITLE
A lot of errors with a Canon 350D

### ISSUE THREAD

**Issue by kasperkamperman** [kritzikratzi/edsdk-processing#1]
- version info: Processing 2.1.1
- EDSDK-4.zip download from your site: http://asdfg.me/up/edsdk-processing/
  (However version info in the console still prints 1.0.3. 
- Windows XP
- EDSKD from Canon: tried 2.7 and 2.11.3 (higher version don't support the 350D, I get a camera not found issue). 

I can't get the image qualities. I can take a picture (camera clicks and stores indeed a picture on the memorycard). However I can't see the picture. 

My code (slightly modified basic example to debug more):
https://gist.github.com/kasperkamperman/c616cf0ce61338e9ca10

Printed in the console when starting:

```
No library found for edsdk.utils.CanonConstants
Java Architecture: x86 - Using EDSDK DLL: EDSDK/Dll/EDSDK.dll
edsdk-processing 1.0.3 by Hansi Raber http://asdfg.me
Running on Java 1.7.0_40/Oracle Corporation (32bit)
print cam: edsdk.processing.ProcessingCanonCamera@46b78d
print Array image qualities: 
An error occurred while getting detailed kEdsPropID_ImageQuality data (error 96: EDS_ERR_INVALID_PARAMETER - Invalid Function Parameter)
null
```

What is remarkable is that the camera is found. But that the array with image qualities returns null. 

When I press the spacebar to take a picture:

```
take picture
Could not check live view status: An error occurred while getting kEdsPropID_Evf_Mode data (error 7: EDS_ERR_NOT_SUPPORTED - Not Supported)
JNA: Callback edsdk.processing.ProcessingCanonCamera@fa391e threw the following exception:
java.lang.NullPointerException
    at edsdk.processing.ProcessingCanonCamera$2.apply(Unknown Source)
    at edsdk.api.CanonCamera.apply(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:445)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:475)
    at com.sun.jna.Native.invokeInt(Native Method)
    at com.sun.jna.Function.invoke(Function.java:344)
    at com.sun.jna.Function.invoke(Function.java:276)
    at com.sun.jna.Library$Handler.invoke(Library.java:216)
    at com.sun.proxy.$Proxy1.DispatchMessage(Unknown Source)
    at edsdk.api.CanonCamera.dispatchMessages(Unknown Source)
    at edsdk.api.CanonCamera.access$000(Unknown Source)
    at edsdk.api.CanonCamera$1.run(Unknown Source)
```

I hope you have any ideas. Are there some version conflicts, is my camera too old? I know the 350D doesn't have live preview. But that is not necessary to store an image isn't it?

Any help is appreciated.

**Comment by kasperkamperman** [comment]
I've tested with a Canon 600D and with that camera it seems to work fine (although live view is really slow).

**Comment by kritzikratzi** [comment]
yea, you get only roughly 6-8 frames/second. that's expected :)
